Story1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' )
]

Story4/urls.py
from django.urls import path
from . import views

app_name= "Story4"
urlpatterns = [
    path('', views.index, name='index' ),
    path('what/', views.what, name='what' )
]

Story5/urls.py
from django.urls import path
from . import views

app_name= "Story5"
urlpatterns = [
    path('', views.courseList, name='courseList' ),
    path('coursedetails/<int:index>/', views.courseDetails, name='courseDetails'),
    path('addcourse/', views.addCourse, name='addCourse')
]

Story6/urls.py
from django.urls import path
from . import views

app_name = "Story6"
urlpatterns = [
    path('', views.activityList, name="activityList"),
    path('addActivity/', views.addActivity, name="addActivity"),
    path('addMember/<int:index>/', views.addMember ,name="addMember"),
]

StoryProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Story4.urls', namespace="Story4")),
    path('mycourses/', include('Story5.urls', namespace="Story5")),
    path('activity/', include('Story6.urls', namespace="Story6")),
    path('admin/', admin.site.urls),
]

Story1/models.py
from django.db import models

# Create your models here.

Story4/models.py
from django.db import models

# Create your models here.

Story5/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    subject     = models.CharField('Subject', max_length=200)
    credit      = models.IntegerField('Credit')
    lecturer    = models.CharField('Lecturer', max_length=200)
    class_room  = models.CharField('Classroom', max_length=200)
    term        = models.IntegerField('Term',)
    description = models.TextField('Description',blank=True)

    def __str__(self):
        return self.subject

Story6/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):
    name = models.CharField("Activity Name" , max_length=200)


class Member(models.Model):
    activity = models.ForeignKey("Activity",on_delete=models.CASCADE, null=True, blank=True)
    member_name = models.CharField("Name", max_length=200)

Story5/forms.py
from .models import Course
from django.forms import ModelForm

class CourseForm(ModelForm):
    required_css_class = "required"
    class Meta:
        model = Course
        fields = "__all__"

Story6/forms.py
from django.forms import ModelForm
from .models import Activity, Member

class ActivityForm(ModelForm):
	required_css_class = "required"
	class Meta:
		model = Activity
		fields = '__all__'
		
class MemberForm(ModelForm):
	class Meta:
		model = Member
		fields = ['member_name']

Story1/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, ('./Story1/index.html'))

Story4/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'index.html')

def what(request):
    return render(request, 'what.html')

Story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Course
from .forms import CourseForm

# Create your views here.

def courseList(request):
    if request.method == "POST":
        Course.objects.get(id=request.POST['id']).delete()
        return redirect('/mycourses/')
    list_course = Course.objects.all()
    return render(request, 'my_courses.html', {'list_course': list_course})

def addCourse(request):
    submitted = False
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = CourseForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request,'add_course.html', {'form':form, 'submitted':submitted})

def courseDetails(request, index):
    course = Course.objects.get(pk=index)
    content = {
        'course' : course
    }
    return render(request, 'course_details.html', content)

Story6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Member
from .forms import ActivityForm, MemberForm

# Create your views here.

def activityList(request):
    activities = Activity.objects.all()
    members = Member.objects.all()
    if request.method == "POST":
        Member.objects.get(id=request.POST['id']).delete()
        return redirect('/activity/')
    
    return render(request, 'activity_list.html', {'activities': activities, 'members': members})

def addActivity(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/activity/')
    else:
        form = ActivityForm()
    return render(request, "add_activity.html", {'form': form})

def addMember(request, index):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            member = Member(activity=Activity.objects.get(id=index), member_name=form.data['member_name'])
            member.save()
            return redirect('/activity/')
    else:
        form = MemberForm()
        
    return render(request, 'add_member.html', {'form': form})

Story1/templates/Story1/base.html
<!DOCTYPE html>

<html lang="en">
{% load static %}
<head>    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Story1/style.css' %}">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

Story1/templates/Story1/index.html
{% extends "./base.html" %}
{% load static %}

{% block title %} Profil page {% endblock %}

{% block content %}
<img src= "{% static 'Story1/FOTO.jpg' %}" alt="Foto Profil"> <br>
<br>
<h2>NAMA:</h2>
<p>Muhammad Haikal Ubaidillah Susanto</p><br>
<br>
<h2>NPM:</h2>
<p>1906350805</p><br>
<br>
<h2>Angkatan:</h2>
<p>2019</p><br>
<br>
<h2>Hobi:</h2>
<p>Playing games and do some coding</p><br>
<br>
<h2>Tempat Kuliah:</h2>
<p>Universitas Indonesia</p><br>
<br>
<h2>Riwayat Pendidikan</h2>
<ul>
    <li>Universitas Indonesia (2019-Sekarang)</li>
    <li>SMA Negeri 68 Jakarta (2016-2019)</li>
    <li>SMP Negeri 216 Jakarta (2013-2017)</li>
</ul>
<br>
<h2>About Me: </h2>
<p>I'm a sophomore computer science student in University of Indonesia. I like to do things in order, one at a time. I do like playing games, especially when it's a strategy games, but i dont like chess.
     In my spare time, i usually read book, whatever it is as long it is not prohibited by law.  </p><br>
<br>

<div class="contact">
    <h2>Contact Me</h2>
    <div class="logo_container">
        <a href="https://line.me/R/ti/p/sabertrone"><img src="{% static 'Story1/LINE_SOCIAL_Basic.png' %}" alt="Line"></a>
    <a href="https://www.instagram.com/haikalsusanto/"><img src="{% static 'Story1/Instagram.svg'%}" alt="Instagram"></a>
    </div>
</div>

{% endblock %}

Story4/templates/index.html
{% extends "base.html" %}

{% load static %}
{% block title %}
Landing Page
{% endblock %}

{% block content %}
<main>
    <section id="home">
        <div class="jumbotron text-center">
            <div class="d-flex flex-column align-items-center mx-auto justify-content-center" >
                <div class="p-2 bd-highlight">
                    <img class="photo" src="{% static 'foto_profil.jpg'%}" alt="foto_profil">
                </div>
                <div class="p-2 bd-highlight">
                    <h2> Hello, I'm</h2>
                    <h1> HAIKAL SUSANTO</h1>
                </div>
            </div>
        </div>
    </section>
    <section id="aboutme" class="container-fluid">
        <div class="section-title text-left">
            ABOUT ME
        </div>
        <div class="ml-4">
            <h1>Biodata</h1>
            <div class="details">
                <h4>FULLNAME</h4>
                <h5>Muhammad Haikal Ubaidillah Susanto</h5>
                <br>
                <h4>NPM</h4>
                <h5>1906350805</h5>
                <br>
                <h4>YEAR ENTRY</h4>
                <h5>2019</h5>
                <br>
                <h4>UNIVERSITY</h4>
                <h5>University Of Indonesia</h5>
                <br>
            </div>
        </div>
        <div class="ml-4">
            <h1>Short Description</h1>
            <div class = "text-justify mr-5 ml-5">
                <h4>I'm a sophomore <b>Computer Science</b> student in <b>University of Indonesia</b>. I like to do things in order, one at a time. 
                    I do like<b> playing games</b>, especially when it's a <b>strategy games</b>, but i dont like chess. 
                    In my spare time, i usually read book, whatever it is as long it is not prohibited by law. 
                    I have a <b>great passion in data science and machine learning</b> because i expect anytime soon that AI will do great things to support humans live.</h4>
                    <br>
                    <br>
            </div>
        </div>

    </section>
    <section id="education" class="container-fluid">
        <div class="section-title mx-auto text-left">
            EDUCATION
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-sm-5 text-center">
                <img class="school" src="{% static 'logo_ui.png'%}" alt="">
            </div>
            <div class="col-sm-5 details">
                <h4>
                    UNIVERSITAS INDONESIA
                </h4>
                <h5>
                    2019-Now
                </h5>
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-sm-5 text-center"">
                <img class="school" src="{% static 'logo_sma.png'%}" alt="">
            </div>
            <div class="col-sm-5 details">
                <h4>
                    SMAN 68 JAKARTA
                </h4>
                <h5>
                    2016-2019
                </h5>
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-sm-5 text-center"">
                <img class="school" src="{% static 'logo_smp.jpg'%}" alt="">
            </div>
            <div class="col-sm-5 details">
                <h4>
                    SMPN 216 JAKARTA
                </h4>
                <h5>
                    2013-2016
                </h5>
            </div>
        </div>
        <br>
        <br>
    </section>
    <section id="contact" class="container-fluid">
        <div class="section-title mx-auto text-left">
            CONTACT ME AT
        </div>
        <div class="d-flex justify-content-center align-items-center flex-row">
            <div class="">
                <a href="mailto:muhammad.haikal91@ui.ac.id" target="_blank"><img class="logo_gmail" src="{% static 'logo_gmail.png' %}" alt=""></a>
            </div>
            <div class="">
                <a href="https://www.instagram.com/haikalsusanto/" target="_blank"><img class="logo_ig" src="{% static 'logo_instagram.png' %}" alt=""></i></a>
            </div>
            <div class="">
                <a href="https://line.me/R/ti/p/sabertrone" target="_blank"><img class="logo" src="{% static 'logo_line.png' %}" alt=""></a>
            </div>
        </div>
    </section>
</main>
{% endblock %}

Story4/templates/what.html
{% extends 'base.html'%}

{% load static %}
{% block title %}
Secret Playlist
{% endblock %}

{% block content %}
<section id="secret" class="container-fluid">
    <div class="section-title text-left">
        Here Is My Secret Playlist
    </div>
    <div class="ml-4">
        <h1>When You Want to Thrive</h1>
        <div class="text-center">
            <iframe src="https://open.spotify.com/embed/playlist/1rOGfeIRY3cGzkHIxhULwO" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class="ml-4">
        <h1>When You Feel Nonsense</h1>
        <div class="text-center">
            <iframe src="https://open.spotify.com/embed/playlist/6SOJ6d47hyLyGjfQ5L2vsv" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
    </div>

</section>
{% endblock %}

Story5/templates/add_course.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Course{% endblock %}

{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
    {% if submitted %}
    <div class="p-5 col-12 text-center">
		Success
	</div>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'Story5:courseList' %}" class="text-white">
			Course List
		</a>
	</button>

    {% else %}
    <div class="section-title mx-auto text-center p-5"> 
		Add New Course
	</div>
    <form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form|crispy }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
    </form>
    
    {% endif %}
</section>
{% endblock %}

Story5/templates/course_details.html
{% extends "base.html" %}
{% block title %}{{ course.subject }} Details{% endblock %}

{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
    <div class="section-title m-auto text-center p-5"> 
        {{ course.subject }}
    </div>
    <table class="table table-bordered mx-5" style="width:90vw">
    <tbody>
        <tr>
            <td> <b> Lecturer </b> </td>
            <td> {{ course.lecturer }} </td>
        </tr>
        <tr>
            <td> <b> Credit </b> </td>
            <td> {{ course.credit }} </td>
        </tr>
        <tr>
            <td> <b> Term </b> </td>
            <td> {{ course.term }} </td>
        </tr>
        <tr>
            <td> <b> Classroom </b> </td>
            <td> {{ course.class_room }} </td>
        </tr>
        <tr>
            <td> <b> Description </b> </td>
            <td> {{ course.description }} </td>
        </tr>
    </tbody>
  </table>

  <button class="btn btn-primary d-flex m-auto click"> 
    <a href="{% url 'Story5:courseList' %}" class="text-white">
        Back to Subject List
    </a>
  </button>
  </section>>

{% endblock %}

Story5/templates/my_courses.html
{% extends "base.html" %}
{% block title %}My Courses{% endblock %}

{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
			Course List
	</div>
	<table class="table table-bordered mx-5" style="width:90vw">
	  <thead class="thead-light text-center">
	    <tr>
	      <th>Course</th>
	      <th>Lecturer</th>
	      <th>Credits</th>
	      <th>Delete</th>
	    </tr>
	  </thead>
		<tbody>
		    {% for course in list_course %}
			<tr>
				<td> <a href="coursedetails/{{ course.id }}">{{ course.subject }} </a> </td>
				<td> {{ course.lecturer }} </td>
				<td class="text-center"> {{ course.credit }} </td>
				<td class="text-center"> 
					<form method="POST" action="{% url 'Story5:courseList' %}">
			          {% csrf_token %}
			          <input name="id" value="{{course.id}}" type="hidden">
			          <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2" style="font-size: 0.8rem;">Delete</button>
			        </form>
				</td>
			</tr>
		    {% endfor %}
		</tbody>
	</table>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'Story5:addCourse' %}" class="text-white">
			Add Course
		</a>
	</button>
</section>

{% endblock %}

Story6/templates/activity_list.html
{% extends "base.html" %}
{% block title %}My Activity{% endblock %}

{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center mt-5">
	<div class="section-title mx-auto text-center mt-5"> 
			Activity List
	  <a href="{% url 'Story6:addActivity' %}" class="text-white">
		<button class="btn btn-primary d-flex mx-auto my-2 click">
			Add Activity
		</button>
	  </a>
	</div>

	<div class="row w-100 justify-content-center">
		{% for activity in activities %}
			<div class="col-4 m-4 p-4 rounded border">
				<ul class="list-group">
				  <li class="list-group-item list-group-item-secondary"> <b> {{ activity.name }} </b> </li>

			      {% for member in members %}
				    {% if member.activity == activity%}
					  	<form method="POST" action="{% url 'Story6:activityList' %}">
					    {% csrf_token %}
					    <input name="id" value="{{member.id}}" type="hidden">
				  		<li class="list-group-item"> 
				  			<div class="d-flex justify-content-between"> 
				  				{{ member.member_name }} 
					          <button type="submit" value="Submit" class="btn btn-primary" style="font-size: 0.8rem;"> 
					          x
					           </button>
					        </form>
				  			</div>
				  		</li>
				    {% endif %}
			      {% endfor %}
				</ul>

				<div class="section-title mx-auto text-center"> 
				  <a href="addMember/{{ activity.id }}" class="text-white">
					<button class="btn btn-primary d-flex mx-auto my-2 click">
					  	Add Member
					</button>
				  </a>
				</div>
			</div>
		{% endfor %}
	</div>

</section>

{% endblock %}

Story6/templates/add_activity.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static%}
{% block title %}Add Activity{% endblock %}

{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		Add Activity
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form|crispy }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>

{% endblock %}

Story6/templates/add_member.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static%}
{% block title %}Add Member{% endblock %}



{% block content %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		Add Your Name
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form|crispy }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://kit.fontawesome.com/d716c5d284.js" crossorigin="anonymous"></script>
    <title>{% block title %}{%endblock%}</title>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-lg fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story4:index' %}#home">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story4:index' %}#aboutme">ABOUT ME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story4:index' %}#education">EDUCATION</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story4:index' %}#contact">CONTACT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story4:what' %}">SECRET PLAYLIST</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story5:courseList' %}">COURSES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Story6:activityList' %}">ACTIVITY</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>